import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { dbConnect } from "@/lib/db/mongo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Auth with NextAuth",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const conn = await dbConnect();
	if (conn) {
		console.log(`Connected db with host: ${conn.connections[0].host}`);
	} else {
		return <p>Something went wrong</p>;
	}

	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
